# Generated by Django 5.2.5 on 2025-09-15 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('---', '---'), ('Снайпинг', 'Снайпинг'), ('Снайпинг МК', 'Снайпинг МК'), ('Силуэтная стрельба', 'Силуэтная стрельба'), ('Практическая стрельба', 'Практическая стрельба')], max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(related_name='competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
