# Generated by Django 5.2.6 on 2025-11-16 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('---', '---'), ('Снайпинг', 'Снайпинг'), ('Снайпинг МК', 'Снайпинг МК'), ('Силуэтная стрельба', 'Силуэтная стрельба'), ('Практическая стрельба', 'Практическая стрельба')], max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('result', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
                ('is_raiting', models.BooleanField(default=False)),
                ('has_winner', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(blank=True, default=None, related_name='competitions', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeminarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(blank=True, default=None, related_name='seminar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SinghtingInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=255)),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='singhting_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('---', '---'), ('Снайпинг', 'Снайпинг'), ('Снайпинг МК', 'Снайпинг МК'), ('Силуэтная стрельба', 'Силуэтная стрельба'), ('Практическая стрельба', 'Практическая стрельба')], max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(blank=True, default=None, related_name='training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
