# Generated by Django 5.2.5 on 2025-09-15 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(related_name='seminar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SinghtingInModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singhting_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('---', '---'), ('Снайпинг', 'Снайпинг'), ('Снайпинг МК', 'Снайпинг МК'), ('Силуэтная стрельба', 'Силуэтная стрельба'), ('Практическая стрельба', 'Практическая стрельба')], max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(related_name='training', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
