# Generated by Django 5.2.6 on 2025-11-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionsmodel',
            name='winner',
        ),
    ]
