# Generated by Django 5.2.5 on 2025-09-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0002_seminarmodel_singhtinginmodel_trainingmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionsmodel',
            name='participants',
            field=models.ManyToManyField(default=None, related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seminarmodel',
            name='participants',
            field=models.ManyToManyField(default=None, related_name='seminar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='singhtinginmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='singhting_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingmodel',
            name='participants',
            field=models.ManyToManyField(default=None, related_name='training', to=settings.AUTH_USER_MODEL),
        ),
    ]
