# Generated by Django 5.2.5 on 2026-01-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topladder',
            name='year_ladder',
            field=models.IntegerField(default=2026),
        ),
    ]
