# Generated by Django 5.2.5 on 2025-09-15 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100, null=True)),
                ('dist', models.CharField(max_length=100, null=True)),
                ('first_try', models.CharField(max_length=100)),
                ('second_try', models.CharField(max_length=100)),
                ('third_try', models.CharField(max_length=100)),
                ('mrad', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableIpAddressSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
